install.packages("tidyverse")
library(tidyverse)
a_cpp <- read.csv("C:\\Users\\sewol\\Documents\\School\\seng480b\\480Bproject\\answers_cpp.csv")
glimpse(a_cpp)
a_python <- read.csv("C:\\Users\\sewol\\Documents\\School\\seng480b\\480Bproject\\answers_python.csv")
glimpse(a_python)
a_java <- read.csv("C:\\Users\\sewol\\Documents\\School\\seng480b\\480Bproject\\answers_java.csv")
glimpse(a_java)
q_cpp <- read.csv("C:\\Users\\sewol\\Documents\\School\\seng480b\\480Bproject\\questions_cpp.csv")
glimpse(q_cpp)
q_python <- read.csv("C:\\Users\\sewol\\Documents\\School\\seng480b\\480Bproject\\questions_python.csv")
glimpse(q_python)
q_java <- read.csv("C:\\Users\\sewol\\Documents\\School\\seng480b\\480Bproject\\questions_java.csv")
glimpse(q_java)

barplot(sort(table(q_cpp$Score), decreasing = TRUE))
min(q_cpp$Score)
max(q_cpp$Score)
barplot(sort(table(q_python$Score), decreasing = TRUE))
min(q_python$Score)
max(q_python$Score)
barplot(sort(table(q_java$Score), decreasing = TRUE))
min(q_java$Score)
max(q_java$Score)
